"""rpy2 oracle backend: call R's SuperLearner with fixed folds.

Purpose: this is the numerical GROUND TRUTH for validating the native backend.
It calls the original R ``CV.SuperLearner`` and returns the SAME
:class:`CVSuperLearnerFit` contract as the native backend, so the two can be
compared learner-for-learner and observation-for-observation.

The key to a meaningful comparison is that BOTH backends use the SAME outer folds.
SuperLearner supports this via ``cvControl = list(V=..., validRows=...)``, where
``validRows`` is a list of the row indices (1-based in R) held out in each outer
fold. We pass the folds generated by ``models.folds.make_folds`` (converted to
1-based). Inner-fold RNG still differs (it only perturbs the learned weights); we
also set an R seed for reproducibility.

!!! IMPORTANT !!!
This module is UNTESTED in the development sandbox because R is not installed
there. It is validated on the user's machine via ``scripts/validate_oracle.py``
(VALIDATION_CHECKLIST V4). Treat it as a careful draft until that passes.

Requires: ``pip install -e '.[oracle]'`` (rpy2) AND a working R with packages:
    SuperLearner, ranger, nnet, xgboost, kernlab, glmnet
"""

from __future__ import annotations

import numpy as np

from ..metrics.cv_metrics import CVSuperLearnerFit
from .folds import make_folds

# The R library specification mirroring get_general_superlearner_cv_model.
_R_SUPERLEARNER_LIBRARY = """
list("SL.mean",
     c("SL.ranger", "screen.glmnet"),
     c("SL.nnet", "screen.glmnet"),
     c("SL.xgboost.hist", "screen.glmnet"),
     c("SL.ksvm", "screen.glmnet"),
     c("SL.lm", "screen.glmnet"))
"""

_R_LM_LIBRARY = 'list("SL.mean", c("SL.lm"))'

# Expected library-column names, matching the native backend's ordering.
_SUPERLEARNER_NAMES = [
    "SL.mean_All", "SL.ranger_screen.glmnet", "SL.nnet_screen.glmnet",
    "SL.xgboost.hist_screen.glmnet", "SL.ksvm_screen.glmnet", "SL.lm_screen.glmnet",
]
_LM_NAMES = ["SL.mean_All", "SL.lm_All"]


def _require_rpy2():
    try:
        import rpy2  # noqa: F401
        import rpy2.robjects  # noqa: F401
    except Exception as exc:  # pragma: no cover
        raise ImportError(
            "The oracle backend needs rpy2 and a working R install. "
            "Install with: pip install -e '.[oracle]'  (and ensure R + the R "
            "packages SuperLearner, ranger, nnet, xgboost, kernlab, glmnet are present)."
        ) from exc


def fit_r_cv_superlearner(
    X: np.ndarray,
    y: np.ndarray,
    *,
    which: str = "superlearner",
    outcome_var: str | None = None,
    outer_v: int = 10,
    inner_v: int = 5,
    seed: int = 1,
    folds: list[np.ndarray] | None = None,
) -> CVSuperLearnerFit:
    """Fit R's CV.SuperLearner and return a :class:`CVSuperLearnerFit`.

    Parameters
    ----------
    which:
        ``"superlearner"`` for the 6-learner library, ``"lm"`` for the mean+lm one.
    folds:
        Outer folds to fix (list of 0-based index arrays). If ``None``, generated
        with ``make_folds(n, outer_v, seed)`` so they match the native default.
    """
    _require_rpy2()
    import rpy2.robjects as ro
    from rpy2.robjects import numpy2ri
    from rpy2.robjects.packages import importr

    numpy2ri.activate()
    importr("SuperLearner")

    X = np.asarray(X, dtype=float)
    y = np.asarray(y, dtype=float)
    n = len(y)

    if folds is None:
        folds = make_folds(n, outer_v, seed=seed)
    names = _SUPERLEARNER_NAMES if which == "superlearner" else _LM_NAMES
    library_r = _R_SUPERLEARNER_LIBRARY if which == "superlearner" else _R_LM_LIBRARY

    # Push data into R.
    ro.globalenv["X_py"] = ro.r["as.data.frame"](X)
    ro.globalenv["y_py"] = ro.FloatVector(y)
    ro.r(f"set.seed({int(seed)})")

    # validRows: list of 1-based index vectors, one per outer fold.
    valid_rows = ro.ListVector(
        {str(i): ro.IntVector((fold + 1).tolist()) for i, fold in enumerate(folds)}
    )
    ro.globalenv["validRows_py"] = valid_rows

    r_script = f"""
    SL.xgboost.hist <- function(...) SL.xgboost(..., params = list(tree_method = "hist"))
    fit <- CV.SuperLearner(
        Y = y_py, X = X_py, family = gaussian(),
        cvControl = list(V = {int(outer_v)}, validRows = validRows_py),
        innerCvControl = list(list(V = {int(inner_v)})),
        SL.library = {library_r},
        saveAll = TRUE, verbose = FALSE
    )
    fit
    """
    fit_r = ro.r(r_script)

    def _get(name):
        return np.asarray(fit_r.rx2(name))

    sl_predict = _get("SL.predict").ravel()
    library_predict = np.asarray(fit_r.rx2("library.predict"))
    discrete = _get("discreteSL.predict").ravel()

    # coef: R stores per-fold weights; extract as (V, n_learners).
    coef = np.asarray(fit_r.rx2("coef"))

    return CVSuperLearnerFit(
        Y=y,
        sl_predict=sl_predict,
        library_predict=library_predict,
        library_names=names,
        folds=folds,
        coef=coef,
        discrete_sl_predict=discrete,
        outcome_var=outcome_var,
        method="method.NNLS",
    )
