"""torch and xgboost must never be loaded in the same process.

torch bundles its own OpenMP runtime (install name /opt/llvm-openmp/lib/libomp.dylib)
and xgboost loads Homebrew's (/opt/homebrew/opt/libomp/lib/libomp.dylib). Once torch
has been imported, an xgboost fit in the same process segfaults (observed with torch
2.14.0 and xgboost 3.3.0 on macOS). The owner's decision (Checkpoint B): RoBERTa
embeddings are generated by a separate step in its own process
(``python -m llm_cong_predict.features.roberta_step``), and the two libraries are never
imported together. No environment workaround such as KMP_DUPLICATE_LIB_OK is used.
See docs/ORCHESTRATION.md.

The guards below run BEFORE the second library would be imported, so a violation
raises a clear error instead of crashing the interpreter.
"""

from __future__ import annotations

import sys


class ProcessIsolationError(RuntimeError):
    """torch and xgboost would be used in the same process."""


def refuse_if_loaded(module: str, action: str) -> None:
    """Raise :class:`ProcessIsolationError` if ``module`` is already imported."""
    if module in sys.modules:
        raise ProcessIsolationError(
            f"{action} refused: '{module}' is already imported in this process. torch and "
            "xgboost load different OpenMP runtimes and crash when used in one process. "
            "Generate RoBERTa embeddings in their own process with "
            "'python -m llm_cong_predict.features.roberta_step' (docs/ORCHESTRATION.md)."
        )
